const DESKTOP_CARDS_DISPLAY_LIMIT = 4;
const TABLET_CARDS_DISPLAY_LIMIT = 2;
const MOBILE_CARDS_DISPLAY_LIMIT = 2;
const MAX_SHORT_FILM_LENGTH = 40;
const EMAIL_VALIDATION =
  "^[A-Za-z0-9\\._%\\+\\-]+@([A-Za-z0-9\\-]+\\.)+[A-Za-z]{2,}$";

const DESKTOP = 1279;
const TABLET = 767;

const DESKTOP_COUNT_CARD = 16;
const TABLET_COUNT_CARD = 8;
const MOBILE_COUNT_CARD = 5;

export {
  DESKTOP_CARDS_DISPLAY_LIMIT,
  TABLET_CARDS_DISPLAY_LIMIT,
  MOBILE_CARDS_DISPLAY_LIMIT,
  MAX_SHORT_FILM_LENGTH,
  EMAIL_VALIDATION,
  DESKTOP,
  TABLET,
  DESKTOP_COUNT_CARD,
  TABLET_COUNT_CARD,
  MOBILE_COUNT_CARD
};
